set_property -dict {PACKAGE_PIN D5 IOSTANDARD LVCMOS33} [get_ports eth_clk]

set_property PACKAGE_PIN E2 [get_ports {vdd_sd_o_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {vdd_sd_o_0}]
set_property PACKAGE_PIN C2 [get_ports {dat_io[0]}]
set_property PACKAGE_PIN E1 [get_ports {dat_io[1]}]
set_property PACKAGE_PIN F1 [get_ports {dat_io[2]}]
set_property PACKAGE_PIN D2 [get_ports {dat_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dat_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dat_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dat_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dat_io[0]}]
set_property PACKAGE_PIN C1 [get_ports cmd_io]
set_property IOSTANDARD LVCMOS33 [get_ports cmd_io]
set_property PACKAGE_PIN B1 [get_ports sd_clk_o_pad_0]
set_property IOSTANDARD LVCMOS33 [get_ports sd_clk_o_pad_0]

set_property PACKAGE_PIN A1 [get_ports {sd_detect_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {sd_detect_0}]